### ISSUE TITLE
Enable restart button if no one wins playing

### ISSUE THREAD

**Issue by ron9817** [ron9817/tic_tac_toe-Game#1]
Restart button by default is disabled. Currently is enabled only when a player wins. Need to enable it if game ens up in draw.

**Comment by RyanWils** [comment]
Hi I would like to solve this issue

**Comment by RyanWils** [comment]
I have submitted a pull request for the above issue. 
While I was looking through the code, I noticed an issue with player X.
There's a specific condition if player X wins diagonally then it wont reveal the rematch button and the game wont end
![image](https://user-images.githubusercontent.com/49354833/66429564-46bc3480-e9e6-11e9-9f7b-8c1e9a3a8398.png)
If you want I can fix this issue as well and add onto the previous commit

**Comment by ron9817** [comment]
Okay please fix the diagonal issue also. Actually in logic i have taken care of that condition also but I think its due to some small syntax or logic mistake the diagonal is not being recognized. In my testing I actually missed this condition. Thank you for finding it.
I am opening a new issue for it.
